name: dont_be_fooled
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_contacts: ^1.1.7+1
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.4
  external_app_launcher: ^3.1.0
  flutter_gemini: ^2.0.5
  flutter_markdown: ^0.6.18
  image_picker: ^1.0.7
  get_it: ^7.6.7
  archive: ^3.6.1
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  go_router: ^13.2.0
  uuid: ^4.3.3
  google_sign_in: ^6.2.1
  receive_whatsapp_chat: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true